version: '3.8'

services:
  bangla-punctuation-api:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "7860:7860"  # Gradio
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./results:/app/results
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - DEBUG=False
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - bangla-punctuation-api
    restart: unless-stopped

volumes:
  redis_data:
